# version: '3.8'
services:
  fe-app:
    image: crpi-vrprd84kar2m221t.cn-hangzhou.personal.cr.aliyuncs.com/hemoumou/he:www
    ports:
      - 80:80
    depends_on:
      - nest-app
    networks:
      - common-network
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    restart: always
    # ports:
    #   - 3005:3005
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - /Users/hmm/mysql-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci # 设置默认字符集  
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: hexin
    ports:
      - 3306:3306  
    restart: always
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - /Users/hmm/redis-data:/data
    ports:
      - 6379:6379  
    restart: always 
    networks:
      - common-network
  minio-container:
    image: bitnami/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - /Users/hmm/minio:/bitnami/minio/data
    environment:
      MINIO_ROOT_USER: hexin
      MINIO_ROOT_PASSWORD: 960716lvwxj
    restart: always 
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
